polkascan/py-substrate-interface

- setup.py
asyncio is part of the python stdlib. This prevents the in built version being overridden by an older version which can cause issues. e.g. on AWS lambda and google cloud function.
> Remove asyncio from pip requirements

- substrateinterface/__init__.py
Typo in serialize_storage_item() cause the metadata to be set incorrectly for a double map
> fix hasher set error

- requirements.txt
- setup.py
- substrateinterface/base.py
- substrateinterface/constants.py
- test/test_query.py
Implement 'well-known' storage keys described in Substrate:
https://github.com/paritytech/substrate/blob/ded44948e2d5a398abcb4e342b0513cb690961bb/primitives/storage/src/lib.rs#L192-L238
And make expose them in the same manner PolkadotJS does: https://github.com/polkadot-js/api/blob/8ba4ed53776a7a71478e229547c7af3d4dc57d63/packages/types/src/metadata/decorate/storage/substrate.ts
Closes #190
> Implemented well-known storage keys in query()

- substrateinterface/base.py
Currently, when making an HTTP request we use the `requests.request` method. This creates a new TCP connection for each request, and can lead to port exhaustion if you're performing many requests.
This PR adds a persistent [Session](https://docs.python-requests.org/en/latest/user/advanced/#session-objects) for HTTP requests so that TCP connections are reused when possible. This avoids port exhaustion and improves performance for HTTP requests.
Fixes #18.
> Reuse TCP connection for HTTP requests

- requirements.txt
- setup.py
- substrateinterface/base.py
- test/test_keypair.py
The update contains message encryption and decryption methods for `Keypair` class. It is compatible with [JavaScript implementation](https://github.com/polkadot-js/common/blob/3597a4eb4e0cf9985104568058c5cd23701bbaed/packages/keyring/src/pair/index.ts#L172). Both implementations produce the same encrypted output for the same keys provided and both can decrypt a message produced by each other. Unlike JavaScript implementation, this one supports ed25519 keys only. Sr25519 support may be implemented in future versions.
PyNaCl package added to dependencies for encryption and decryption functionality as the most well-supported alternative to tweetnacl [used](https://github.com/polkadot-js/common/blob/3597a4eb4e0cf9985104568058c5cd23701bbaed/packages/util-crypto/src/nacl/seal.ts#L4) in …
> Message encryption and decryption methods

- README.md
- docs/base.html
- docs/index.html
- requirements.txt
- setup.py
- substrateinterface/base.py
- test/test_create_extrinsics.py
To initiate and finalize multisig extrinsics, the following helper functions are available:
```python
keypair_alice = Keypair.create_from_uri('//Alice', ss58_format=substrate.ss58_format)
multisig_account = substrate.generate_multisig_account(
signatories=[
keypair_alice.ss58_address, 
'5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty', 
'5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y'
], 
threshold=2
)
```
Then initiate the multisig extrinsic by providing the call and a keypair of one of its signatories:
```python
call = substrate.compose_call(
call_module='System',
call_function='remark_with_event',
call_params={
'remark': 'Multisig test'
}
)
extrinsic = substrate.create_multisig_extrinsic(call, keypair_alice, multisig_account, era={'period': 64})
receipt = …
```
> Multisig helper functions

- substrateinterface/base.py
Substrate RPC now always returns `WeightV1`
> Check if weight needs to be converted to `WeightV2`

- substrateinterface/base.py
Uncaught exception when runtime doesn't support `WeightV2`. These older runtimes don't need to convert the Weight from `int` to `WeightV2` struct
> Gracefully pass when WeightV2 type not detected

- substrateinterface/base.py
- test/test_helper_functions.py
Currently, the function always encodes to `ss58_format` of connected network. A way to override this is desired.
> Custom ss58_format for ss58_encode()

- docs/examples.md
- docs/reference/storage.md
- docs/usage/subscriptions.md
- examples/storage_subscription.py
- mkdocs.yml
- substrateinterface/base.py
- substrateinterface/storage.py
- substrateinterface/utils/encrypted_json.py
- substrateinterface/utils/hasher.py
- test/test_query.py
- test/test_query_map.py
- test/test_subscriptions.py
See #327 
Usage example:
```python
def subscription_handler(storage_key, updated_obj, update_nr, subscription_id):
print(f"Update for {storage_key.params[0]}: {updated_obj.value}")
storage_keys = [
substrate.create_storage_key(
"System", "Account", ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]
),
substrate.create_storage_key(
"System", "Account", ["5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty"]
)
]
result = substrate.subscribe_storage(
storage_keys=storage_keys, subscription_handler=subscription_handler
)
```
> Add method to subscribe to multiple storage keys at once

- substrateinterface/base.py
Looks like original code expected subscription events to arrive earlier than subscription id, e.g.:
```
{subscription: 1, result: ...}
{subscription: 1}
{subscription: 1, result: ...}
```
But there were two problems:
1. removing processed messages was skipping some messages
2. always reading before checking queued messages delayed those messages processing
> Fix rpc message order

- substrateinterface/contracts.py
The current implementation doesn't support WeightV2 when upload_code == false
> calculate weight when upload_code==false

- docs/usage/query-storage.md
- examples/storage_subscription.py
- substrateinterface/base.py
- substrateinterface/storage.py
- test/test_query.py
Example:
```python
storage_keys = [
substrate.create_storage_key(
"System", "Account", ["F4xQKRUagnSGjFqafyhajLs94e7Vvzvr8ebwYJceKpr8R7T"]
),
substrate.create_storage_key(
"System", "Account", ["GSEX8kR4Kz5UZGhvRUCJG93D5hhTAoVZ5tAe6Zne7V42DSi"]
),
substrate.create_storage_key(
"Staking", "Bonded", ["GSEX8kR4Kz5UZGhvRUCJG93D5hhTAoVZ5tAe6Zne7V42DSi"]
)
]
result = substrate.query_multi(storage_keys)
for storage_key, value_obj in result:
print(storage_key, value_obj)
```
> Added query_multi() function

- examples/create_and_exec_contract.py
- examples/extensions.py
- requirements.txt
- setup.py
- substrateinterface/contracts.py
- test/test_contracts.py
> Upgrade contract interface to support WeightV2

- substrateinterface/base.py
- substrateinterface/contracts.py
- test/test_contracts.py
- test/test_runtime_call.py
It's often useful to `read` contracts at old blocks. For this it's necessary to be able to make runtime calls at old blocks. The appropriate RPC call in substrate supports this option -- this PR is adding the support here. 
I'm sorry if I missed something, like bumping version, running linter or things like that, but I wasn't sure how to do these things.
> Add support for runtime calls at other blocks than the most recent.

- substrateinterface/base.py
- test/test_query_map.py
Possibility to omit multiple parameters when using `query_map`, which was bound to only the last parameter. 
For example:
```python
result = self.kusama_substrate.query_map(
module='ConvictionVoting',
storage_function='VotingFor',
max_results=10
)
print([record for record in result])
```
Closes #350
> Added multiple params as key support for query_map

- substrateinterface/base.py
- test/test_init.py
Added `strict_scale_decode` flag to be more tolerant for example remaining SCALE bytes.
```python
substrate = SubstrateInterface(url=URL, config={'strict_scale_decode': False})
```
> strict_scale_decode config flag

- substrateinterface/base.py
- substrateinterface/contracts.py
- test/test_query.py
* Fixed generate PalletVersion storage key
* Determine correct `ContractExecResult` by PalletVersion
Fixes #368
> Determine correct ContractExecResult by PalletVersion

- substrateinterface/utils/ecdsa_helpers.py
When running `test_keypais.py`, I get:
```
FAILED test/test_keypair.py::KeyPairTestCase::test_create_ecdsa_keypair_mnemonic - AttributeError: 'mpz' object has no attribute 'to_bytes'
FAILED test/test_keypair.py::KeyPairTestCase::test_create_ecdsa_keypair_uri - AttributeError: 'mpz' object has no attribute 'to_bytes'
FAILED test/test_keypair.py::KeyPairTestCase::test_sign_and_verify_ecdsa - AttributeError: 'mpz' object has no attribute 'to_bytes'
FAILED test/test_keypair.py::KeyPairTestCase::test_sign_and_verify_invalid_signature_ecdsa - AttributeError: 'mpz' object has no attribute 'to_bytes'
FAILED test/test_keypair.py::KeyPairTestCase::test_sign_and_verify_public_ethereum_address - AttributeError: 'mpz' object has no attribute 'to_bytes'
```
It seems to be due to `BIP32_CURVE.order()` …
> (fix) mpz has no attribute to_bytes py311

- substrateinterface/contracts.py
A possible fix for https://github.com/polkascan/py-substrate-interface/issues/379
> Decode only ContractEmitted events from the origin contract

- requirements.txt
The latest version is 4.1.1 and there isn't any change that doesn't work with the library
> Increase max version allowed for eth-utils

- requirements.txt
- setup.py
- substrateinterface/base.py
- test/test_create_extrinsics.py
The `CheckMetadataHash` signed extension enables the new metadata hash verification feature that was approved as
[RFC78](https://polkadot-fellows.github.io/RFCs/approved/0078-merkleized-metadata.html).
See https://github.com/polkadot-fellows/runtimes/pull/337
This PR only allow mode is `Disabled` for now, but ensures compatibility with upcoming Kusama/Polkadot release.
> CheckMetadataHash signed extension support

- setup.py
In #388 I edited the requirements.txt and didn't notice that the requirements are hardcoded in the setup.py. This PR is to have the same version in both
https://github.com/polkascan/py-substrate-interface/blob/43ad00cca215dfafd4607be6440aecd198ee6089/requirements.txt#L10
Would you consider using `pyproject.toml` instead of setup.py to avoid this errors? Also setup.py is being deprecated afaik.
> Update version of eth-utils to match requirements

- requirements.txt
- setup.py
web3.py requires in the new version 7 to have eth-utils version 5. To make them both compatible I increase the allowed version here
> Bump eht-utils to allow version 5
